import type { DevTeam, RosterPosition } from "@prisma/client";

/**
 * Source: internal dev-department org sheet. Used only when the DB is empty (see seed.ts).
 * hireRaw: d/m/y, y-m-d, or y/m/d as on the sheet; empty / or \ → no date.
 */
export type MasaratRosterRow = {
  id?: string;
  displayName: string;
  workEmail: string | null;
  phone: string | null;
  jobTitle: string;
  skills: string;
  tenureLabel: string | null;
  hireRaw: string | null;
  rosterPosition: RosterPosition;
  team: DevTeam | null;
  isTeamLead: boolean;
};

export function parseHireDate(raw: string | null | undefined): Date | null {
  if (raw == null) return null;
  const s = String(raw).trim();
  if (s === "" || s === "/" || s === "\\") return null;
  if (/^\d{4}-\d{2}-\d{2}/.test(s)) {
    const day = s.slice(0, 10).split("-").map(Number);
    if (day.length === 3 && day[0] != null && day[1] != null && day[2] != null) {
      return new Date(Date.UTC(day[0], day[1] - 1, day[2]));
    }
  }
  if (/^\d{4}\/\d{1,2}\/\d{1,2}/.test(s)) {
    const head = s.split(/[T\s]/)[0] ?? s;
    const [y, mo, d] = head.split("/").map(Number);
    if (y != null && mo != null && d != null) return new Date(Date.UTC(y, mo - 1, d));
  }
  const m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);
  if (m) {
    const d = Number(m[1]);
    const mo = Number(m[2]);
    const y = Number(m[3]);
    return new Date(Date.UTC(y, mo - 1, d));
  }
  const t = new Date(s);
  return Number.isNaN(t.getTime()) ? null : t;
}

function em(s: string | null | undefined): string | null {
  if (s == null) return null;
  const t = s.trim();
  if (t === "" || t === "/" || t === "\\") return null;
  return t.toLowerCase();
}

const ID_HEAD = "00000000-0000-4000-8000-000000000001";
const ID_ASST = "00000000-0000-4000-8000-000000000002";

/** Stable IDs for the two app operators (match former seed lead/assistant dev ids). */
const raw: MasaratRosterRow[] = [
  {
    id: ID_HEAD,
    displayName: "أنس جمال سالم المصباحي",
    workEmail: em("a.almesbahi@masarat.ly"),
    phone: "914257887",
    jobTitle: "Director of Programming and Development Management",
    skills: "Leadership, department strategy",
    tenureLabel: "7 years, 0 months",
    hireRaw: "17/12/2018",
    rosterPosition: "department_head",
    team: null,
    isTeamLead: false,
  },
  {
    id: ID_ASST,
    displayName: "فيروز عادل محمد بشير",
    workEmail: em("f.basher@masarat.ly"),
    phone: "917177652",
    jobTitle: "Technical Assistant",
    skills: "Coordination, documentation",
    tenureLabel: "2 years, 4 months",
    hireRaw: "27/8/2023",
    rosterPosition: "department_assistant",
    team: null,
    isTeamLead: false,
  },
  {
    displayName: "محمد عبد السلام محمد العمارية",
    workEmail: em("m.alemmaria@masarat.ly"),
    phone: "915781702",
    jobTitle: "Back-End Manager",
    skills: "Back-End, leadership",
    tenureLabel: "5 years, 5 months",
    hireRaw: "20/7/2020",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: true,
  },
  {
    displayName: "عبد السلام ابراهيم البشير عويد",
    workEmail: em("a.awid@masarat.ly"),
    phone: "913851607",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "5 years, 6 months",
    hireRaw: "05/07/2020",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "إسلام عمر مصطفى القريتلي",
    workEmail: em("i.ghretlli@masarat.ly"),
    phone: "911530301",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "4 years, 1 month",
    hireRaw: "7/12/2021",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "اسراء عبد الباسط على صوان",
    workEmail: em("e.sowan@masarat.ly"),
    phone: "927525812",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "2 years, 4 months",
    hireRaw: "20/8/2023",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "نضال علي محمد الخرباش",
    workEmail: em("nidal.elkharbash@masarat.ly"),
    phone: "916138193",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "3 years, 6 months",
    hireRaw: "1/7/2022",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "رشاد عبد العاطي إبراهيم شيوب",
    workEmail: em("r.shayhoub@masarat.ly"),
    phone: "911287325",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "2 years, 3 months",
    hireRaw: "3/10/2023",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "شهاب الدين أفلح عمر المقصي",
    workEmail: em("s.almuqgsi@masarat.ly"),
    phone: "928251714",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "2 years, 5 months",
    hireRaw: "8/8/2023",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "انس محسن معمر الحمدي",
    workEmail: em("a.alhimadi@masarat.ly"),
    phone: "927716247",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "0 years, 1 month",
    hireRaw: "2026-02-22",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "محمد عبد الباسط صوان",
    workEmail: em("m.sowan@masarat.ly"),
    phone: "946824010",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "0 years, 0 months",
    hireRaw: "2026/04/12",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "طه احمد محمد رضوان",
    workEmail: em("t.radwan@masarat.ly"),
    phone: "913084044",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "0 years, 0 months",
    hireRaw: "2026-03-29",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "محمد حسن حسين ابوسدرة",
    workEmail: em("m.sidrah@masarat.ly"),
    phone: "944463915",
    jobTitle: "Back-End",
    skills: "Back-End",
    tenureLabel: "0 years, 0 months",
    hireRaw: "2026-04-07",
    rosterPosition: "member",
    team: "backend",
    isTeamLead: false,
  },
  {
    displayName: "علي خالد جمعه الحجاج",
    workEmail: em("a.alhajaj@masarat.ly"),
    phone: "923507580",
    jobTitle: "Front-End (Web) Manager",
    skills: "Front-End (Web), leadership",
    tenureLabel: "3 years, 3 months",
    hireRaw: "3/10/2022",
    rosterPosition: "member",
    team: "frontend_web",
    isTeamLead: true,
  },
  {
    displayName: "ملاك محسن معمر الحمدي",
    workEmail: em("m.alhamdi@masarat.ly"),
    phone: "910206373",
    jobTitle: "Front-End (Web) (Angular, Flutter)",
    skills: "Angular, Flutter, web",
    tenureLabel: "7 years, 4 months",
    hireRaw: "10/9/2018",
    rosterPosition: "member",
    team: "frontend_web",
    isTeamLead: false,
  },
  {
    displayName: "أمال محمد مسعود البوعيشي",
    workEmail: em("a.abouashe@masarat.ly"),
    phone: "928807812",
    jobTitle: "Front-End (Web) (Angular, Flutter)",
    skills: "Angular, Flutter, web",
    tenureLabel: "8 years, 10 months",
    hireRaw: "12/3/2017",
    rosterPosition: "member",
    team: "frontend_web",
    isTeamLead: false,
  },
  {
    displayName: "نصر الطاهر نصر الصويعي",
    workEmail: em("n.swei@masarat.ly"),
    phone: "934531467",
    jobTitle: "Front-End",
    skills: "Front-End (Web)",
    tenureLabel: "0 years, 0 months",
    hireRaw: null,
    rosterPosition: "member",
    team: "frontend_web",
    isTeamLead: false,
  },
  {
    displayName: "هدى الهادي عمر عمر",
    workEmail: em("h.omar@masarat.ly"),
    phone: "928387202",
    jobTitle: "Front-End (Web) (Angular)",
    skills: "Angular, web",
    tenureLabel: "0 years, 1 month",
    hireRaw: "2026-02-17",
    rosterPosition: "member",
    team: "frontend_web",
    isTeamLead: false,
  },
  {
    displayName: "موحي الدين محمود شعبان عقيلة",
    workEmail: em("mo.agila@masarat.ly"),
    phone: "927956556",
    jobTitle: "Front-End (Web) (Flutter)",
    skills: "Flutter, web",
    tenureLabel: "0 years, 1 month",
    hireRaw: "2026-02-19",
    rosterPosition: "member",
    team: "frontend_web",
    isTeamLead: false,
  },
  {
    displayName: "جهاد احمد المبروك",
    workEmail: em("j.almabrouk@masarat.ly"),
    phone: "913523276",
    jobTitle: "Front-End (Web) (Angular)",
    skills: "Angular, web",
    tenureLabel: "0 years, 1 month",
    hireRaw: "23/11/2025",
    rosterPosition: "member",
    team: "frontend_web",
    isTeamLead: false,
  },
  {
    displayName: "زياد خالد سعد الشريف",
    workEmail: em("z.sherif@masarat.ly"),
    phone: "918603047",
    jobTitle: "Front-End (Web) (Angular)",
    skills: "Angular, web",
    tenureLabel: "0 years, 0 months",
    hireRaw: "21/12/2025",
    rosterPosition: "member",
    team: "frontend_web",
    isTeamLead: false,
  },
  {
    displayName: "إلياس خالد عبد الحفيظ المغبوب",
    workEmail: em("e.elmaghbub@masarat.ly"),
    phone: "911946685",
    jobTitle: "Front-End (Mobile) Manager",
    skills: "Front-End (Mobile), leadership",
    tenureLabel: "2 years, 6 months",
    hireRaw: "2/7/2023",
    rosterPosition: "member",
    team: "frontend_mobile",
    isTeamLead: true,
  },
  {
    displayName: "محمد ابراهيم علي الصول",
    workEmail: em("m.assoul@masarat.ly"),
    phone: "910461043",
    jobTitle: "Front-End (Mobile)",
    skills: "Mobile (iOS, Android)",
    tenureLabel: "2 years, 6 months",
    hireRaw: "2/7/2023",
    rosterPosition: "member",
    team: "frontend_mobile",
    isTeamLead: false,
  },
  {
    displayName: "زكريا فتحى خليفة ابو رتيمة",
    workEmail: em("z.abuirtaymah@masarat.ly"),
    phone: "916399126",
    jobTitle: "Front-End (Mobile)",
    skills: "Mobile (iOS, Android)",
    tenureLabel: "2 years, 5 months",
    hireRaw: "30/7/2023",
    rosterPosition: "member",
    team: "frontend_mobile",
    isTeamLead: false,
  },
  {
    displayName: "نعيم فتحي الطيف",
    workEmail: em("n.ltayef@masarat.ly"),
    phone: "912965097",
    jobTitle: "Front-End (Mobile)",
    skills: "Mobile (iOS, Android)",
    tenureLabel: "1 year, 2 months",
    hireRaw: "20/10/2024",
    rosterPosition: "member",
    team: "frontend_mobile",
    isTeamLead: false,
  },
  {
    displayName: "حمزة عبدالباسط محمود لياس",
    workEmail: em("h.layas@masarat.ly"),
    phone: "914206969",
    jobTitle: "Front-End (Mobile)",
    skills: "Mobile (iOS, Android)",
    tenureLabel: "0 years, 1 month",
    hireRaw: "2026-02-19",
    rosterPosition: "member",
    team: "frontend_mobile",
    isTeamLead: false,
  },
  {
    displayName: "محمد جمال صالح اللافي",
    workEmail: null,
    phone: "922917708",
    jobTitle: "Front-End (Mobile)",
    skills: "Mobile (iOS, Android)",
    tenureLabel: "0 years, 0 months",
    hireRaw: null,
    rosterPosition: "member",
    team: "frontend_mobile",
    isTeamLead: false,
  },
  {
    displayName: "يونس مصطفى يونس بالخير",
    workEmail: em("y.belkher@masarat.ly"),
    phone: "918612613",
    jobTitle: "Front-End (Mobile)",
    skills: "Mobile (iOS, Android)",
    tenureLabel: "0 years, 0 months",
    hireRaw: null,
    rosterPosition: "member",
    team: "frontend_mobile",
    isTeamLead: false,
  },
  {
    displayName: "اسلام عبد العاطي إبراهيم شيوب",
    workEmail: null,
    phone: "913011832",
    jobTitle: "Front-End (Mobile)",
    skills: "Mobile (iOS, Android)",
    tenureLabel: "0 years, 0 months",
    hireRaw: null,
    rosterPosition: "member",
    team: "frontend_mobile",
    isTeamLead: false,
  },
  {
    displayName: "سراج الدين إسماعيل محمد أبودابر",
    workEmail: em("s.abudaber@masarat.ly"),
    phone: "923650452",
    jobTitle: "Quality Assurance Manager",
    skills: "QA, leadership",
    tenureLabel: "5 years, 6 months",
    hireRaw: "5/7/2020",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: true,
  },
  {
    displayName: "مصعب زهير محمد سويسي",
    workEmail: em("m.swissi@masarat.ly"),
    phone: "923497337",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "6 years, 6 months",
    hireRaw: "2/7/2019",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "صفاء سالم محمد دخيلة",
    workEmail: em("s.dakhila@masarat.ly"),
    phone: "928867037",
    jobTitle: "Quality Assurance / Documentation",
    skills: "QA, documentation",
    tenureLabel: "6 years, 11 months",
    hireRaw: "29/1/2019",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "محمد النوري خليفة خليفة",
    workEmail: em("m.khalifa@masarat.ly"),
    phone: "925448508",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "2 years, 7 months",
    hireRaw: "14/5/2023",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "أزر محمد علي الدوكالي",
    workEmail: em("a.aldoukali@masarat.ly"),
    phone: "916631663",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "2 years, 7 months",
    hireRaw: "13/6/2023",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "أصيل الصيد عريبي المجعى",
    workEmail: em("a.almagi@masarat.ly"),
    phone: "911159223",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "0 years, 10 months",
    hireRaw: "23/2/2025",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "هاشم صلاح إبراهيم الفتحلي",
    workEmail: em("h.alfathali@masarat.ly"),
    phone: "944124579",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "0 years, 10 months",
    hireRaw: "9/3/2025",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "مصعب الطاهر مصطفى اندير",
    workEmail: em("m.ender@masarat.ly"),
    phone: "918887725",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "0 years, 11 months",
    hireRaw: "13/2/2025",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "محمد عبدالحميد علي التومي",
    workEmail: em("m.altoumi@masarat.ly"),
    phone: "924879356",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "0 years, 0 months",
    hireRaw: "2026/01/18",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "رمزي يوسف فرج الطرابلسي",
    workEmail: em("r.trabelse@masarat.ly"),
    phone: "918596164",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "0 years, 0 months",
    hireRaw: "2026-03-11",
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "محمد احسين عبدالواحد الازرق",
    workEmail: em("m.alazraq@masarat.ly"),
    phone: "922285368",
    jobTitle: "Quality Assurance",
    skills: "QA, testing",
    tenureLabel: "0 years, 0 months",
    hireRaw: null,
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
  {
    displayName: "منار عبد الباسط احمد بن رحومة",
    workEmail: em("m.benrhuma@masarat.ly"),
    phone: "910241716",
    jobTitle: "Quality Assurance / Documentation",
    skills: "QA, documentation",
    tenureLabel: "0 years, 0 months",
    hireRaw: null,
    rosterPosition: "member",
    team: "qa",
    isTeamLead: false,
  },
];

export const MASARAT_ROSTER: MasaratRosterRow[] = raw;
